/**
 * @fileoverview gRPC-Web generated client stub for akushon_interfaces.proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: akushon.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.akushon_interfaces = {};
proto.akushon_interfaces.proto = require('./akushon_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.akushon_interfaces.proto.ConfigClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.akushon_interfaces.proto.ConfigPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.akushon_interfaces.proto.Empty,
 *   !proto.akushon_interfaces.proto.ConfigActions>}
 */
const methodDescriptor_Config_GetConfig = new grpc.web.MethodDescriptor(
  '/akushon_interfaces.proto.Config/GetConfig',
  grpc.web.MethodType.UNARY,
  proto.akushon_interfaces.proto.Empty,
  proto.akushon_interfaces.proto.ConfigActions,
  /**
   * @param {!proto.akushon_interfaces.proto.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.akushon_interfaces.proto.ConfigActions.deserializeBinary
);


/**
 * @param {!proto.akushon_interfaces.proto.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.akushon_interfaces.proto.ConfigActions)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.akushon_interfaces.proto.ConfigActions>|undefined}
 *     The XHR Node Readable Stream
 */
proto.akushon_interfaces.proto.ConfigClient.prototype.getConfig =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/akushon_interfaces.proto.Config/GetConfig',
      request,
      metadata || {},
      methodDescriptor_Config_GetConfig,
      callback);
};


/**
 * @param {!proto.akushon_interfaces.proto.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.akushon_interfaces.proto.ConfigActions>}
 *     Promise that resolves to the response
 */
proto.akushon_interfaces.proto.ConfigPromiseClient.prototype.getConfig =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/akushon_interfaces.proto.Config/GetConfig',
      request,
      metadata || {},
      methodDescriptor_Config_GetConfig);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.akushon_interfaces.proto.ConfigActions,
 *   !proto.akushon_interfaces.proto.Empty>}
 */
const methodDescriptor_Config_SaveConfig = new grpc.web.MethodDescriptor(
  '/akushon_interfaces.proto.Config/SaveConfig',
  grpc.web.MethodType.UNARY,
  proto.akushon_interfaces.proto.ConfigActions,
  proto.akushon_interfaces.proto.Empty,
  /**
   * @param {!proto.akushon_interfaces.proto.ConfigActions} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.akushon_interfaces.proto.Empty.deserializeBinary
);


/**
 * @param {!proto.akushon_interfaces.proto.ConfigActions} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.akushon_interfaces.proto.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.akushon_interfaces.proto.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.akushon_interfaces.proto.ConfigClient.prototype.saveConfig =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/akushon_interfaces.proto.Config/SaveConfig',
      request,
      metadata || {},
      methodDescriptor_Config_SaveConfig,
      callback);
};


/**
 * @param {!proto.akushon_interfaces.proto.ConfigActions} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.akushon_interfaces.proto.Empty>}
 *     Promise that resolves to the response
 */
proto.akushon_interfaces.proto.ConfigPromiseClient.prototype.saveConfig =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/akushon_interfaces.proto.Config/SaveConfig',
      request,
      metadata || {},
      methodDescriptor_Config_SaveConfig);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.akushon_interfaces.proto.SetJointsData,
 *   !proto.akushon_interfaces.proto.Empty>}
 */
const methodDescriptor_Config_publishSetJoints = new grpc.web.MethodDescriptor(
  '/akushon_interfaces.proto.Config/publishSetJoints',
  grpc.web.MethodType.UNARY,
  proto.akushon_interfaces.proto.SetJointsData,
  proto.akushon_interfaces.proto.Empty,
  /**
   * @param {!proto.akushon_interfaces.proto.SetJointsData} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.akushon_interfaces.proto.Empty.deserializeBinary
);


/**
 * @param {!proto.akushon_interfaces.proto.SetJointsData} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.akushon_interfaces.proto.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.akushon_interfaces.proto.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.akushon_interfaces.proto.ConfigClient.prototype.publishSetJoints =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/akushon_interfaces.proto.Config/publishSetJoints',
      request,
      metadata || {},
      methodDescriptor_Config_publishSetJoints,
      callback);
};


/**
 * @param {!proto.akushon_interfaces.proto.SetJointsData} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.akushon_interfaces.proto.Empty>}
 *     Promise that resolves to the response
 */
proto.akushon_interfaces.proto.ConfigPromiseClient.prototype.publishSetJoints =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/akushon_interfaces.proto.Config/publishSetJoints',
      request,
      metadata || {},
      methodDescriptor_Config_publishSetJoints);
};


export default proto.akushon_interfaces.proto;

